# Configurations for generate `docker-compose.yml`
global:
  infinite: false
  resolve: true

env: &default
  interface: ens192
  image: php:alpine
  #host_address: 201

networks:
  - name: vlan20
    <<: *default
    vlan_id: 20
    subnet: 192.168.20.0/24
    gateway: 192.168.20.1
    ipv4_address: 192.168.20.201
  - name: vlan30
    <<: *default
    vlan_id: 30
    subnet: 192.168.30.0/24
    gateway: 192.168.30.1
    ipv4_address: 192.168.30.201
